// Pure-function tests for the audit-report HTML template
// (DEMO_THESIS.md UC1 beat 8). No lib/soe, no lib/rules, no fetch — every
// test here hands buildAuAuditReportHtml a synthetic, hand-built
// AuditReportInput and asserts on the returned string directly. The golden
// end-to-end figures (962/87/74/61·19·7, both demo anchors) are pinned in
// app/api/report/route.test.ts instead, against the real fixture.

import { describe, expect, it } from 'vitest';
import { buildAuAuditReportHtml, type AuditReportInput, type AuditReportRow } from './report-template';

function row(overrides: Partial<AuditReportRow> = {}): AuditReportRow {
  return {
    accountLabel: 'Nguyen household · ••4821',
    primaryHolder: 'Linh Nguyen',
    authorizedUser: 'Minh Nguyen',
    ruleShortName: 'R1 · Product Eligibility',
    finding: 'Secured card · deposit $500.00 · AU added Mar 14, 2024',
    addedDate: 'Mar 14, 2024',
    ...overrides,
  };
}

function baseInput(overrides: Partial<AuditReportInput> = {}): AuditReportInput {
  return {
    generatedAt: 'Aug 5, 2026',
    policyTitle: 'Authorized User Eligibility Policy',
    scanned: 962,
    exceptions: 2,
    accountsAffected: 2,
    byRule: [
      {
        ruleId: 'R1',
        title: 'R1 — Product Eligibility',
        requirement:
          'An authorized user may not be added to, or maintained on, a secured card account.',
        citation: 'Authorized User Eligibility Policy · §Product Eligibility',
        count: 1,
      },
      {
        ruleId: 'R2',
        title: 'R2 — Account Standing',
        requirement:
          'An authorized user may not be added to an account that is not in good standing at the time of addition.',
        citation: 'Authorized User Eligibility Policy · §Account Standing',
        count: 1,
      },
    ],
    rows: [row(), row({ accountLabel: 'Patel household · ••1190', ruleShortName: 'R2 · Account Standing' })],
    ...overrides,
  };
}

describe('buildAuAuditReportHtml — structure and content', () => {
  it('is a complete, self-contained HTML document', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
    expect(html).toContain('<html lang="en">');
    expect(html).toContain('<style>');
    expect(html).not.toMatch(/<link\s/);
    expect(html).not.toMatch(/<script\s/);
    expect(html).not.toMatch(/https?:\/\//);
  });

  it('renders the header — title, generated date, policy document name', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).toContain('Cardinal &middot; Authorized-User Policy Audit');
    expect(html).toContain('Aug 5, 2026');
    expect(html).toContain('Authorized User Eligibility Policy');
  });

  it('marks the executive summary with the D2 narrative-slot comment and states the real figures', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).toContain('<!-- narrative: live-model slot (D2) — scripted constant for the demo -->');
    expect(html).toContain('962 accounts carrying');
    expect(html).toContain('identified 2 exceptions across 2 accounts');
  });

  it('renders the headline stat tiles and every rule card (title, requirement, citation, count)', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).toContain('Accounts scanned');
    expect(html).toContain('Exceptions');
    expect(html).toContain('Accounts affected');
    for (const rule of baseInput().byRule) {
      expect(html).toContain(rule.title);
      expect(html).toContain(rule.requirement);
      expect(html).toContain(rule.citation);
    }
  });

  it('renders exactly one <tr> per header row plus one per data row', () => {
    const input = baseInput({ rows: [row(), row(), row()] });
    const html = buildAuAuditReportHtml(input);
    const trCount = (html.match(/<tr/g) ?? []).length;
    expect(trCount).toBe(1 + input.rows.length);
  });

  it('renders every exception row field: account, primary holder, authorized user, rule, finding, added date', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).toContain('Nguyen household · ••4821');
    expect(html).toContain('Linh Nguyen');
    expect(html).toContain('Minh Nguyen');
    expect(html).toContain('R1 · Product Eligibility');
    expect(html).toContain('Secured card · deposit $500.00 · AU added Mar 14, 2024');
    expect(html).toContain('Mar 14, 2024');
  });

  it('renders the print-repeat table header rule and @page margins', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).toMatch(/thead\s*\{[^}]*display:\s*table-header-group/);
    expect(html).toMatch(/@page\s*\{[^}]*margin/);
  });

  it('renders the fixed footer verbatim', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).toContain('Generated by Cardinal ops agent &middot; human-approved &middot; demo data');
  });

  it('omits the remediation section entirely when remediation is not provided', () => {
    const html = buildAuAuditReportHtml(baseInput());
    expect(html).not.toContain('Remediation Executed');
    expect(html).not.toContain('Confirmation id');
  });

  it('renders the remediation section — figures, confirmationId verbatim, human-operator actor, timestamp', () => {
    const html = buildAuAuditReportHtml(
      baseInput({
        remediation: {
          removed: 87,
          accountsTouched: 74,
          notificationsQueued: 74,
          confirmationId: 'rem-rpt-au-20260805-deadbeef',
          approvedAt: 'Aug 5, 2026',
        },
      }),
    );
    expect(html).toContain('Remediation Executed');
    expect(html).toContain('>87<');
    expect(html).toContain('>74<');
    expect(html).toContain('rem-rpt-au-20260805-deadbeef');
    expect(html).toContain('Approved by a human operator');
    expect(html).toContain('Aug 5, 2026');
  });

  it('escapes HTML-significant characters in free-text fields', () => {
    const html = buildAuAuditReportHtml(
      baseInput({
        rows: [
          row({
            authorizedUser: 'Pat "Junior" <Smith> & Co',
            finding: 'A & B < C > "quoted"',
          }),
        ],
      }),
    );
    expect(html).toContain('Pat &quot;Junior&quot; &lt;Smith&gt; &amp; Co');
    expect(html).toContain('A &amp; B &lt; C &gt; &quot;quoted&quot;');
    expect(html).not.toContain('<Smith>');
    expect(html).not.toContain('A & B < C > "quoted"');
  });

  it('is deterministic — the same input produces byte-identical output', () => {
    const input = baseInput();
    const first = buildAuAuditReportHtml(input);
    const second = buildAuAuditReportHtml(input);
    expect(second).toBe(first);
  });
});
